default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: discover_manga_dev

test:
  <<: *default
  database: discover_manga_test

production:
  <<: *default
  database: discover_manga_prod
  username: discover_manga_user
  password: <%= ENV["DISCOVER_MANGA_DATABASE_PASSWORD"] %>
